### ISSUE TITLE
Slow info update

### ISSUE THREAD

**Issue by DedMsk** [hassbian-ABC/homebridge-MiHumidifier#1]
Hello!

Thanks for the this plugin. Work fine.

**But I have tell some bugs...**

Info about % and water level
In MiHome app I see correct info about this, but in Homekit this info update very slow and not correct.

![photo_2019-04-24_11-29-56](https://user-images.githubusercontent.com/4592572/56644797-1a556b80-6685-11e9-80ce-d95a8aeed39f.jpg)![photo_2019-04-24_11-30-01](https://user-images.githubusercontent.com/4592572/56644805-1cb7c580-6685-11e9-8c14-1cd14145d4ef.jpg)

**New features request....**

Is it possible to create a push notification when the water level approaches the minimum value?
Or do it through a virtual sensor

**Comment by hassbian-ABC** [comment]
fixed bug that humidifier water level  display inaccurate.
