### ISSUE TITLE
zhimi.humidifier.cb1

### ISSUE THREAD

**Issue by motaker** [hassbian-ABC/homebridge-MiHumidifier#4]
Hi I have zhimi.humidifier.**cb1** model and successfully added the humidifier to homekit thanks to this plugin. 

but I have realized that temperature sensor showing 0 degC and water level is not able to find in Humidifier's setting menu. Do you have any idea why it is not working ? it is due to the model is not **ca1 but cb1** ? Is there any way to work it correctly ?

Here is my configuration.
{
      			"accessory": "MiHumidifier",
      			"name": "Humidifier",
      			"ip": "xxx.xxx.x.xx",
      			"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      			"showTemperatureDisable": false,
      			"showTemperatureSensorName": "SmartMi Temp."
},
![IMG-1716](https://user-images.githubusercontent.com/40581042/60820236-53d84600-a1a1-11e9-9830-47b9444af922.JPG)
![IMG-1715](https://user-images.githubusercontent.com/40581042/60820237-53d84600-a1a1-11e9-8e16-0d7561ba6a33.JPG)

**Comment by hassbian-ABC** [comment]
CB1 has been added   @motaker

**Comment by motaker** [comment]
Hi, Thank you fro your help.
Now I can see water level in humidifier's setting menu.
but still temperature shows incorrectly.

here is my config now. what could be reason for this ?

{
"accessory": "MiHumidifier",
"name": "Humidifier",
"ip": "xxx.xxx.x.xx",
"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"model": "cb1",
"showTemperatureDisable": false,
"showTemperatureSensorName": "SmartMi Temp."
},

![IMG-1750](https://user-images.githubusercontent.com/40581042/61558933-b7e3ef80-aa68-11e9-9ef0-9ef139cd2492.JPG)

**Comment by hassbian-ABC** [comment]
@motaker
It has been repaired
Update version 0.1.3

**Comment by motaker** [comment]
It is working Perfectly. Thank you very much !
