### ISSUE TITLE
Is ca1 with firmware 1.6.7.1032 supported?

### ISSUE THREAD

**Issue by dimuravyev** [hassbian-ABC/homebridge-MiHumidifier#5]

**Comment by Krocko** [comment]
Do you really have the 1.6.**7**.1032?
For me the actual firmware is 1.6.**6**.1032.

**Comment by DJay-X** [comment]
Works great. 
![7F51F3CA-B8D7-4378-8EF4-E1A10F4B2ED9](https://user-images.githubusercontent.com/3874239/64761863-61150680-d53d-11e9-8423-98a6d7acd60c.png)

**Comment by Krocko** [comment]
Strange. @DJay-X how long you have this firmware?

**Comment by DJay-X** [comment]
A week or two. Not recently.

**Comment by Krocko** [comment]
@DJay-X: yesterday I got the update.
